apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deployment
  labels:
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
