apiVersion: v1
kind: Service
metadata:
  labels:
    tier: frontend
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080 #-37676 #optional will be added randomly if not given 
  selector:
    tier: frontend
